// Mocks generated by Mockito 5.4.2 from annotations
// in store_client/test/domain/test_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:store_client/src/domain/repository/library_repository.dart'
    as _i2;
import 'package:store_client/src/domain/repository/messenger_repository.dart'
    as _i3;
import 'package:store_client/src/domain/repository/user_data_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LibraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryRepository extends _i1.Mock implements _i2.LibraryRepository {}

/// A class which mocks [MessengerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessengerRepository extends _i1.Mock
    implements _i3.MessengerRepository {}

/// A class which mocks [UserDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRepository extends _i1.Mock
    implements _i4.UserDataRepository {}
